//Todos os automoveis standart do stand
automoveis = [
    {
    id: 1,
    modelo: "Model S",
    marca: "Tesla", 
    combustivel: "Elétrico",
    cor: "Branco", 
    preco: 80000, 
    estado: "Novo",
    mes: "Janeiro",
    ano: 2023,
    quilometros: 5000,
    foto: "./assets/Tesla-Model-S_1.webp",
    telefone: "912345678",
    descricao: "Sofisticado veículo elétrico com alta autonomia.Carroçaria: Sedan, Portas: 4, Lugares: 5. Velocidade Máxima: 250 km/h, Aceleração dos 0-100 km/h em 3.1 segundos. Motor elétrico de 404 kW. Tracção integral, Tipo de caixa: automática, Capacidade de Mala: 793 litros.",
    telefone: "912345678",
    email: "stand@altamente.com"
    },
    {
    id: 2,
    modelo: "Civic",
    marca: "Honda",
    combustivel: "Gasolina",
    cor: "Azul",
    preco: 25000,
    estado: "Usado",
    mes: 'Março',
    ano: 2019,
    quilometros: 35000,
    foto: "./assets/civic-sport-azul.png",
    descricao: "Confiável e eficiente, perfeito para o dia a dia. Carroçaria: Utilitário, Portas: 4, Lugares: 5. Velocidade Máxima: 220 km/h, Aceleração dos 0-100 km/h em 8.5 segundos. Motor de 134 kW. Tracção dianteira, Tipo de caixa: manual. Capacidade de Mala: 478 litros.",
    telefone: "912345678",
    email: "stand@altamente.com"
    },
    {
    id: 3,
    modelo: "Corolla",
    marca: "Toyota",
    combustivel: "Híbrido",
    cor: "Cinzento",
    preco: 30000,
    estado: "Semi-novo",
    mes: 'Agosto',
    ano: 2021,
    quilometros: 20000,
    foto: "./assets/corolla.jpg",
    descricao: "Confortável e económico, ótimo para longas viagens. Carroçaria: Hatchback, Portas: 5, Lugares: 5. Velocidade Máxima: 180 km/h, Aceleração dos 0-100 km/h em 10.5 segundos. Motor híbrido de 112 kW. Tracção dianteira, Tipo de caixa: automática. Capacidade de Mala: 361 litros",
    telefone: "912345678",
    email: "stand@altamente.com"
    },
    {
    id: 4,
    modelo: "Mustang GT",
    marca: "Ford",
    combustivel: "Gasolina",
    cor: "Vermelho",
    preco: 60000,
    estado: "Novo",
    mes: 'Junho',
    ano: 2023,
    quilometros: 1000,
    foto: "./assets/Ford Mustang GT.jpg",
    descricao: "Carro desportivo potente com um design icônico. Carroçaria: Coupé, Portas: 2, Lugares: 4. Velocidade Máxima: 250 km/h, Aceleração dos 0-100 km/h em 4.3 segundos. Motor de 450 kW. Tracção traseira, Tipo de caixa: manual. Capacidade de Mala: 408 litros.",
    telefone: "912345678",
    email: "stand@altamente.com"
    },
    {
    id: 5,
    modelo: "Golf GTI",
    marca: "Volkswagen",
    combustivel: "Gasolina",
    cor: "Preto",
    preco: 35000,
    estado: "Usado",
    mes: 'Novembro',
    ano: 2020,
    quilometros: 25000,
    foto: "./assets/golf.jpg",
    descricao: "Compacto esportivo, une desempenho e praticidade. Carroçaria: Hatchback, Portas: 5, Lugares: 5. Velocidade Máxima: 238 km/h, Aceleração dos 0-100 km/h em 6.5 segundos. Motor de 180 kW. Tracção dianteira, Tipo de caixa: automática. Capacidade de Mala: 380 litros.",
    telefone: "912345678",
    email: "stand@altamente.com"
    },
    {
    id: 6,
    modelo: "Wrangler",
    marca: "Jeep",
    combustivel: "Gasolina",
    cor: "Verde",
    preco: 45000,
    estado: "Semi-novo",
    mes: 'Julho',
    ano: 2022,
    quilometros: 15000,
    foto: "./assets/jeep_wrangler.png",
    descricao: "SUV robusto para aventuras off-road. Carroçaria: SUV, Portas: 4, Lugares: 5. Velocidade Máxima: 190 km/h, Aceleração dos 0-100 km/h em 7.6 segundos. Motor de 280 kW. Tracção integral, Tipo de caixa: automática. Capacidade de Mala: 547 litros.",
    telefone: "912345678",
    email: "stand@altamente.com"
    },
    {
    id: 7,
    modelo: "A6",
    marca: "Audi",
    combustivel: "Gasóleo",
    cor: "Cinzento",
    preco: 50000,
    estado: "Novo",
    mes: 'Dezembro',
    ano: 2023,
    quilometros: 3000,
    foto: "./assets/audi_a6.jpg",
    descricao: "Luxo e tecnologia com motor potente e design sofisticado. Carroçaria: Sedan, Portas: 4, Lugares: 5. Velocidade Máxima: 245 km/h, Aceleração dos 0-100 km/h em 5.8 segundos. Motor de 370 kW. Tracção integral, Tipo de caixa: automática. Capacidade de Mala: 530 litros.",
    telefone: "912345678",
    email: "stand@altamente.com"
    }
    ];